algoritmo "carro"
// Função : solicitar se pode passar ou nao
// Autor : Caio Victor
// Data : 22/06/2020
// Seção de Declarações 
var
idade: inteiro
resp:caracter
inicio
//entrada
escreval("Qual sua idade: ")
leia(idade)

escreval("Possui habilitação: ")
leia(resp)

//decisão
se ((idade>=)e(resp="sim")) entao

escreval("Pode passar!")
senao
escreval("Não pode passar!")

fimse
fimalgoritmo
